api:
  api-prefix: /api/v1
  strip-prefix: 2

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:8080
          predicates:
            - Path=${api.api-prefix}/identity/**
          filters:
            - StripPrefix=${api.strip-prefix}
        - id: profile-service
          uri: http://localhost:8081
          predicates:
            - Path=${api.api-prefix}/profile/user-profiles/**
          filters:
            - StripPrefix=${api.strip-prefix}

server:
  port: 8888